```{r}
impl_step_wise <- function(sample_data, initial_graph=NULL, max_iters=20){
  ###
  # step wise algorithm impl
  # param sample_data: data.frame 
  # param initial_graph: matrix
  # param max_iters: int
  # utils function
  util_state_cal <- function(a_matrix, state, i, j ){
    switch(state,
           # state 1 means i->j
           {
             a_matrix[i,j] = 1
             a_matrix[j,i] = 0
           },
           # state 2 means no link between i and j
           {
             a_matrix[i,j] = 0
             a_matrix[j,i] = 0             
           },
           # state 3 means j->i
           {
             a_matrix[i,j] = 0
             a_matrix[j,i] = 1             
           }
           )
    a_matrix
  }
  
  n = dim(sample_data)[2]
  
  # create initial matrix if no graph input
  if (is.null(initial_graph)){
    initial_graph = matrix(0,n,n)  # create initial graph according to numnode
  }
  
  # check validity
  if (dim(initial_graph)[2] != n){
    stop('Illegel argument exception, two parameter column size should equal')
  }
  
  next_posible_graphs = list()  # place to hold all the posible steps
  next_bics = c()  # place to hold all the bic generated by graphs
  cur_graph = initial_graph
  cur_bic = graph_estimation(cur_graph, sample_data)$total_bic
  states = 3  #fixed, only 3 states in one point
  iter = 0
  
  repeat {
    for (i in 2:n) {
      for (j in 1:(i-1)) {
        for (state in 1:states) {
          tmp_next_graph = util_state_cal(cur_graph,state, i, j)  # change state
          if (is.acyclic(tmp_next_graph)){
            # store this matrix
            next_posible_graphs = append(next_posible_graphs, list(tmp_next_graph))
            # calculate bic and store
            bic = graph_estimation(tmp_next_graph, sample_data)$total_bic
            next_bics = c(next_bics, bic)
          }
        }
      }
    }
    
    iter = iter +1
    if (cur_bic <= min(next_bics)|| iter>max_iters)
      break
    else {
      cur_bic = min(next_bics)
      cur_graph = next_posible_graphs[[which.min(next_bics)]]
    }
  }
  
  result = list()
  result[['cur_graph']] = cur_graph
  result[['cur_bic']] = cur_bic
  
  result
}
```

```{r}
# 124 126
num = 350
result = impl_step_wise(gene, graph[[num]], 1000)
print(result$cur_graph)
print(graph[[num]])
print(result$cur_bic)
```



